public with sharing class QuoteLineItemTriggerManager {
    public Static Boolean ALLOWSUPPORTPRODUCT = true;
    public Static Boolean ALLOWTRIGGERPROCESS = true; 
    public Static Boolean ALLOWQUOTETRIGERPROCESS = true;
    public Static Boolean ALLOWROOTNODECREATION = true;
    public Static Boolean ALLOWPRODUCTUPDATE = true;
    public Static Boolean ALLOWQUOTELINEUPDATE = true;
    public Static Boolean ALLOWSUPPORTPRODENTRY = true;
    public Static Boolean INITIALINSERT = false;
}