@isTest(SeeAllData=true)
public class RHX_TEST_Milestone1_Time {
	//static testMethod void RHX_Testmethod() {
       // List<sObject> sourceList = [SELECT Id 
		//	FROM Milestone1_Time__c LIMIT 1];
       // if(sourceList.size() == 0) {
       //     sourceList.add(
       //             new Milestone1_Time__c()
       //     );
 //       }
    	//rh2.ParentUtil.UpsertRollupTestRecords( sourceList );
//    }
}